name: Setup SSH Access to Runner

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-ssh:
    runs-on: blacksmith-2vcpu-ubuntu-2204 # Change to your custom runner label
    timeout-minutes: 360  # Max runtime of 6 hours
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
